version: "3.8"
services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
      - "7861:7861"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: 
      jupyter-lab --ip 0.0.0.0 --allow-root --NotebookApp.token=''
      
